<a href="https://colab.research.google.com/github/Ozah-Blessing/Hamoye_Quiz_Answer/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


code to print the type of array


In [ ]:
arr=[6,7,8,9]
print(type(arr))

<class 'list'>


In [ ]:
a=np.array(arr)
print(type(a))

<class 'numpy.ndarray'>


a is a 1d array with 4 items

In [ ]:
print(a.shape)

(4,)


In [ ]:
print(a.dtype)

int64


Get the Dimension of a using *ndim*

In [ ]:
print(a.ndim)

1


In [ ]:
b=np.array([[1,2,3],[4,3,6]])
print(b)

[[1 2 3]
 [4 3 6]]


In [ ]:
print (b.ndim)

2


In [ ]:
print (b.shape)

(2, 3)


In [ ]:
c=np.array([[9.0,8.0,7.0],[1.0,2.0,3.0]])
d=np.array([[4.0,5.0,6.0],[9.0,8.0,7.0]])
c+d

array([[13., 13., 13.],
       [10., 10., 10.]])

In [ ]:
c*d

array([[36., 40., 42.],
       [ 9., 16., 21.]])

In [ ]:
5/d

array([[1.25      , 1.        , 0.83333333],
       [0.55555556, 0.625     , 0.71428571]])

In [ ]:
c**2

array([[81., 64., 49.],
       [ 1.,  4.,  9.]])

**INDEXING WITH ARRAY**

In [ ]:
a[0]

6

In [ ]:
a[3]

9

In [ ]:
b[0,0]

1

In [ ]:
b[1,2]

6

In [ ]:
c[0,1]

8.0

In [ ]:
d[1, 0:2]

array([9., 8.])

**SLICING**


In [ ]:
e=np.array([[10,11,12],[13,14,15],[16,17,18],[19,20,21]])
e[0:3, 0:2]

array([[10, 11],
       [13, 14],
       [16, 17]])

In [ ]:
e[-1]

array([19, 20, 21])

In [ ]:
e[0:2, 2]

array([12, 15])

#INTEGER INDEXING* 


In [ ]:
e[[2,0,3,2],[2,1,0,1]]

array([18, 11, 19, 17])

# Boolean Indeexinn

In [ ]:
e[e>115]

array([], dtype=int64)