<a href="https://colab.research.google.com/github/Ozah-Blessing/Hamoye_Quiz_Answer/blob/main/Strings_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print ('ilove coding')

ilove coding


In [ ]:
first_name= 'godwin'
print (f"hello {first_name}")

hello godwin


In [ ]:
first_name= 'godwin'
print (first_name.title())

Godwin


In [ ]:
word = "amimal"
print (word[0])

a


In [ ]:
first_name = "ayomide"
print (first_name.title())

Ayomide


In [ ]:
first_name = "ayomide"
print (first_name.upper())

AYOMIDE


In [ ]:
first_name = "ayomide"
print (first_name.replace('a', 'J'))

Jyomide


In [ ]:
sentence = "ayomide is a good boy"
print (sentence.find('good'))

13


In [ ]:
x=10
y=15
if x > y:
 print ('x is greater that y')
else:
   print ('y is greater than x')

y is greater than x


In [ ]:
x=100
y=10
if x > y:
 print ('x is greater that y')
elif x==y:
  print ('x is equal to y')
else:
  print ('y is greater than x')

x is greater that y


In [ ]:
list1 = [2, 9.7, 'word', 'True']
print(list1[1])

9.7


In [ ]:
list2=['dog', 'rice', 'beans', ('fish','goat'), 70]
print(list2[2])

beans


In [ ]:
list2=list1
print(list2[3])

True


In [ ]:
student1= ['godwin', 24, 'computer scinece']
print(student1)
student1[1]=25
print(student1)

['godwin', 24, 'computer scinece']
['godwin', 25, 'computer scinece']


In [ ]:
prices=[5,11,4,5,8,9]
prices.sort()
print(prices)

[4, 5, 5, 8, 9, 11]


In [ ]:
list1 = [2, 9.7, 'word', 'True']
print(type(list1))

<class 'list'>


In [ ]:
weeks= ["monday", "tuesday", "wednesday"]
weeks.append("thursday")
print(weeks)

['monday', 'tuesday', 'wednesday', 'thursday']


In [ ]:
weeks= ["monday", "tuesday", "wednesday"]
weeks.extend(["thursday"])
print(weeks)

['monday', 'tuesday', 'wednesday', 'thursday']


In [ ]:
x=10
while x>0:
 print(x)
 x=x-1
print("go!")

In [ ]:
x=10
while x>0:
 print(x)
 x=x-1
 print('go!')
 

10
go!
9
go!
8
go!
7
go!
6
go!
5
go!
4
go!
3
go!
2
go!
1
go!


In [ ]:
x=0
n=10
while x<=10
 print(x)

SyntaxError: ignored

In [ ]:
x=0
n=10
while x<=n:
 print(x)
 if x==4:
   break
   x=x+1

Streaming output truncated to the last 5000 lines.
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0

In [ ]:
x=0
n=10
while x<=n:
 print(x)
 if x==4:
   break
   x=x+1
 print(x)
 

In [ ]:
n=5
while n>0:
  n-=1
  if n==2:
    continue
    print(n)
  print ('Loop ended.')

In [ ]:
x=0
n=10
while x<=n:
 print(x)
 if x==4:
   break
  x=x+1

In [ ]:
D={'name':'Bob', 'age':'25', 'job':'Dev'}
X=D.pop('age')
print(D)

{'name': 'Bob', 'job': 'Dev'}


In [ ]:
def print_arguments(*args):
  print(args)
print_arguments(1,5,10,11,2)

(1, 5, 10, 11, 2)


In [5]:
import pandas as pd

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/WalePhenomenon/climate_change/master/fuel_ferc1.csv")

In [ ]:
df

record_id  ...  fuel_cost_per_mmbtu
0        f1_fuel_1994_12_1_0_7  ...                1.121
1       f1_fuel_1994_12_1_0_10  ...                1.120
2        f1_fuel_1994_12_2_0_1  ...                1.650
3        f1_fuel_1994_12_2_0_7  ...                1.970
4       f1_fuel_1994_12_2_0_10  ...                2.570
...                        ...  ...                  ...
29518  f1_fuel_2018_12_12_0_13  ...                9.030
29519   f1_fuel_2018_12_12_1_1  ...                6.950
29520  f1_fuel_2018_12_12_1_10  ...                8.990
29521  f1_fuel_2018_12_12_1_13  ...                1.110
29522  f1_fuel_2018_12_12_1_14  ...               11.680

[29523 rows x 11 columns]

In [ ]:
df.head(5)

record_id  ...  fuel_cost_per_mmbtu
0   f1_fuel_1994_12_1_0_7  ...                1.121
1  f1_fuel_1994_12_1_0_10  ...                1.120
2   f1_fuel_1994_12_2_0_1  ...                1.650
3   f1_fuel_1994_12_2_0_7  ...                1.970
4  f1_fuel_1994_12_2_0_10  ...                2.570

[5 rows x 11 columns]

In [ ]:
import numpy as np

In [ ]:
a = [2,3,4]

In [ ]:
print (a)

[2, 3, 4]


In [ ]:
b = np.array(a)

In [ ]:
print (b)

[2 3 4]


In [ ]:
b*2

array([4, 6, 8])

In [ ]:
c = np.array([3,4,5])

In [ ]:
c

array([3, 4, 5])

In [ ]:
b + c

array([5, 7, 9])

In [ ]:
d = np.array([2,5])

In [ ]:
print(type(b))

<class 'numpy.ndarray'>


In [ ]:
a = 1
print (type(a))

<class 'int'>


In [ ]:
s = np.array([[[2,3,4],[1,5,7],[1,5,9],[2,5,7]], [[2,3,4],[1,5,7],[1,5,9],[2,5,7]]])
print (s)
print (s.shape)

[[[2 3 4]
  [1 5 7]
  [1 5 9]
  [2 5 7]]

 [[2 3 4]
  [1 5 7]
  [1 5 9]
  [2 5 7]]]
(2, 4, 3)


In [ ]:

s.ndim

3

In [ ]:
def print_arguments(*args):
 print(args)
print_arguments(1, 5,0, 10)

(1, 5, 0, 10)


In [ ]:
class car:
  def__int__(self)
  pass

NameError: ignored

In [ ]:
def square(x):
  result=x*x
  return result
  square(5)
print(result


NameError: ignored

In [ ]:
import math
print(math.sqrt(4))

2.0


In [ ]:
import math
print(math.pow(2,2))

4.0


In [ ]:
list1=[2,9.7,'word', True]
print(list1[2])

word


In [2]:
import pandas as pd
df= pd.read_csv("https://raw.githubusercontent.com/WalePhenomenon/climate_change/master/fuel_ferc1.csv")
df

record_id  ...  fuel_cost_per_mmbtu
0        f1_fuel_1994_12_1_0_7  ...                1.121
1       f1_fuel_1994_12_1_0_10  ...                1.120
2        f1_fuel_1994_12_2_0_1  ...                1.650
3        f1_fuel_1994_12_2_0_7  ...                1.970
4       f1_fuel_1994_12_2_0_10  ...                2.570
...                        ...  ...                  ...
29518  f1_fuel_2018_12_12_0_13  ...                9.030
29519   f1_fuel_2018_12_12_1_1  ...                6.950
29520  f1_fuel_2018_12_12_1_10  ...                8.990
29521  f1_fuel_2018_12_12_1_13  ...                1.110
29522  f1_fuel_2018_12_12_1_14  ...               11.680

[29523 rows x 11 columns]

In [31]:
import pandas as pd
fuel_data= pd.read_csv("https://raw.githubusercontent.com/WalePhenomenon/climate_change/master/fuel_ferc1.csv")
fuel_data

record_id  ...  fuel_cost_per_mmbtu
0        f1_fuel_1994_12_1_0_7  ...                1.121
1       f1_fuel_1994_12_1_0_10  ...                1.120
2        f1_fuel_1994_12_2_0_1  ...                1.650
3        f1_fuel_1994_12_2_0_7  ...                1.970
4       f1_fuel_1994_12_2_0_10  ...                2.570
...                        ...  ...                  ...
29518  f1_fuel_2018_12_12_0_13  ...                9.030
29519   f1_fuel_2018_12_12_1_1  ...                6.950
29520  f1_fuel_2018_12_12_1_10  ...                8.990
29521  f1_fuel_2018_12_12_1_13  ...                1.110
29522  f1_fuel_2018_12_12_1_14  ...               11.680

[29523 rows x 11 columns]

In [45]:
g=fuel_data.groupby('fuel_unit')
g

In [46]:
for fuel_unit, fuel_unit_fuel_data in g:
  print(fuel_unit)
  print(fuel_unit_fuel_data)

bbl
                     record_id  ...  fuel_cost_per_mmbtu
14       f1_fuel_1994_12_6_0_2  ...                5.469
19      f1_fuel_1994_12_6_0_14  ...                5.770
21       f1_fuel_1994_12_6_1_8  ...                5.187
23      f1_fuel_1994_12_6_1_11  ...                5.604
25      f1_fuel_1994_12_6_1_14  ...                5.605
...                        ...  ...                  ...
29502  f1_fuel_2018_12_191_1_9  ...               15.174
29505  f1_fuel_2018_12_432_0_2  ...               17.790
29506  f1_fuel_2018_12_432_0_5  ...               16.590
29507  f1_fuel_2018_12_432_0_8  ...               17.160
29514   f1_fuel_2018_12_12_0_4  ...                9.970

[7998 rows x 11 columns]
gal
                      record_id  ...  fuel_cost_per_mmbtu
7933    f1_fuel_2000_12_20_0_10  ...              8.32400
7934    f1_fuel_2000_12_20_0_13  ...              8.41000
9062    f1_fuel_2001_12_20_0_10  ...              7.80700
9063    f1_fuel_2001_12_20_0_13  ...              

In [33]:
fuel_data.duplicated().any()

False

In [36]:
fuel_data.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...  
29518    False
29519    False
29520    False
29521    False
29522    False
Length: 29523, dtype: bool

In [39]:
fuel_data.fuel_type_code_pudl.duplicated().sum()

29517

In [41]:
fuel_data.duplicated().sum()


0

In [42]:
fuel_data.shape

(29523, 11)

In [43]:
fuel_data.drop_duplicates(keep='first').shape






(29523, 11)

check that the length of both datafram sum to the expected length


In [32]:
fuel_df1=fuel_data.iloc[0:19000].reset_index(drop=True)
fuel_df2=fuel_data.iloc[19000:].reset.index(drop=True)
assert len(fuel_data)==(len(fuel_df1)+len(fuel_df2))

AttributeError: ignored

In [23]:
fuel_data.groupby('fuel_type_code_pud1').first()

KeyError: ignored

In [6]:
fuel_data.isnull().sum()

record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64

In [7]:
fuel_data.groupby('fuel_unit')['fuel_unit'].count()

fuel_unit
bbl        7998
gal          84
gramsU      464
kgU         110
mcf       11354
mmbtu       180
mwdth        95
mwhth       100
ton        8958
Name: fuel_unit, dtype: int64

In [11]:
fuel_data[['fuel_unit']]=fuel_data[['fuel_unit']].fillna(value='mcf')

In [12]:
fuel_data.isnull().sum()

record_id                       0
utility_id_ferc1                0
report_year                     0
plant_name_ferc1                0
fuel_type_code_pudl             0
fuel_unit                       0
fuel_qty_burned                 0
fuel_mmbtu_per_unit             0
fuel_cost_per_unit_burned       0
fuel_cost_per_unit_delivered    0
fuel_cost_per_mmbtu             0
dtype: int64

In [13]:
fuel_data.groupby('report_year')['report_year'].count()

report_year
1994    1235
1995    1201
1996    1088
1997    1094
1998    1107
1999    1050
2000    1373
2001    1356
2002    1205
2003    1211
2004    1192
2005    1269
2006    1243
2007    1264
2008    1228
2009    1222
2010    1261
2011    1240
2012    1243
2013    1199
2014    1171
2015    1093
2016    1034
2017     993
2018     951
Name: report_year, dtype: int64

In [22]:
fuel_data.groupby('fuel_type_code_pud1').first()

KeyError: ignored